### ISSUE TITLE
Unable to get past "Tare" screen

### ISSUE THREAD

**Issue by designingsean** [damariei/wiiscale#2]
I can get the Balance board to connect, but when I reach the "Press button to tare and step on" I cannot get anything else to happen. I have tried pressing both the front button and the red button on the balance board, neither of which have any impact.

OSX 10.8
XCode 4.4.1

I did allow it to upgrade the source from 3.1 to 3.2, which I suppose could be the issue. I don't have time right this second to revert back to 3.1 and build that, but there were no errors in the build (just a few warnings), so I am not sure that has anything to do with it. However, I will try later tonight and report back if that has any impact.

**Comment by damariei** [comment]
There was an issue with the bluetooth framework and OSX 10.8
I pushed a quick fix for it so it should be resolved, closing issue.
